spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:timeattack'
    username: 'user'
    password: ''
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'

  data:
    redis:
      port: 6379