spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_MYSQL_URL}
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
      password: ${DEV_REDIS_PASSWORD}

kakao:
  client-id: ${DEV_KAKAO_CLIENT_ID}
  client-secret: ${DEV_KAKAO_CLIENT_SECRET}
  redirect-uri: ${DEV_KAKAO_REDIRECT_URI}


